spring:
  profiles:
    active: cloud
    
spring:
    profiles: cloud

server:
  port: 8082

eureka:
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true